# ARTWORK
# Secrets that can be set via files in `./secrets/*.secret`, via command line by `--set 'pgAdminUser=xyz,pgHost=host.com,...'` or even uncomment them in the lines below.
# pgAdminUser: ''
# pgHost: ''
# pgHostRO: ''
# pgPass: ''
# pgPassRO: ''
# pgPassTeam: ''
# pgPassRep: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipSecret (will not attempt to create PG secret
# skipPostgres (will not attempt to create patroni postgres)
# skipBackupsPV (will not attempt to create backups PV)
# skipBackups (will not attempt to create backups cronjob)
# skipNamespace (will skip creating devstats namespace)
#
# skipSecret: 1
# skipPostgres: 1
# skipBackupsPV: 1
# skipBackups: 1
# skipNamespace: 1
#
# Other evrironment options
# backupsImage: 'lukaszgryglicki/devstats-prod'
# backupsOnlyDBs: 'kubernetes prometheus fluentd'
# debug: 1
# overwritePostgresCommand: true
# postgresCommand: 'sleep'
# postgresCommandArgs:
#   - "36000"
# postgresImageName: 'jberkus/simple-patroni:v3'
# postgresImageName: 'lukaszgryglicki/devstats-patroni'
# postgresImageName: 'lukaszgryglicki/devstats-patroni-new'
# storageAccessModes: ReadWriteMany
# storageClass: efs
# storageClass: gp2
# storageClass: openebs-hostpath
# storageClass: nfs-openebs-localstorage
# storageClass: local-storage
# backupCommandArgs:
#   - "backupsarg"
# Backup into different node-group.
backupsNodeSelector:
  lfda: elastic
dbNodeSelector:
  lfda: devstats
backupsCron: '45 3 * * *'
backupsCronHistoryLimit: 2
backupsCommand: 'backup.sh'
backupsOnlyDBs: ''
backupsImage: 'lukaszgryglicki/devstats-test'
backupsPodName: 'devstats-backups'
backupsPVName: 'devstats-backups'
backupsPVSize: '160Gi'
backupsRestartPolicy: Never
#backupsStorageAccessModes: ReadWriteOnce
backupsStorageAccessModes: ReadWriteMany
# backupsStorageClass: 'local-storage'
backupsStorageClass: 'nfs-openebs-localstorage'
concurrencyPolicy: Forbid
fullnameOverride: devstats
imagePullPolicy: Always
limitsBackupsCPU: '2000m'
limitsBackupsMemory: '2Gi'
limitsPostgresCPU: '5000m'
limitsPostgresMemory: '48Gi'
name: devstats
namespace: 'devstats'
nameOverride: devstats
oauthSecret: github-oauth
patroniLoopWait: 15
patroniTtl: 60
patroniRetryTimeout: 60
patroniMasterStartTimeout: 600
patroniMaximumLagOnFailover: 5368709120
pgSecret: pg-db
projectsFile: 'devstats-helm/projects.yaml'
projectsOverride: ''
provisionCommand: './devstats-helm/deploy_all.sh'
provisionImage: 'lukaszgryglicki/devstats-test'
provisionPodName: devstats-provision
provisionRestartPolicy: Never
postgresSvcName: 'devstats-postgres'
postgresImageName: 'lukaszgryglicki/devstats-patroni-new'
postgresStorageSize: '2800Gi'
postgresNodes: 4
postgresSharedBuffers: '96GB'
postgresMaxConn: 1024
postgresMaxParallelWorkersPerGather: 12
postgresMaxWorkerProcesses: 56
postgresMaxParallelWorkers: 56
postgresWorkMem: '2GB'
postgresWalBuffers: '128MB'
postgresMaxTempFile: '50GB'
postgresUseSlots: true
postgresHotStandby: 'on'
postgresWalLogHints: 'on'
postgresWalKeepSegments: 10
postgresWalLevel: 'hot_standby'
postgresMaxWalSenders: 5
postgresMaxReplicationSlots: 5
prodServer: ''
pvName: devstats-pvc
reinitDropDB: ''
reportsPod: ''
reportsPodName: 'devstats-reports'
reportsCommand: '/bin/sleep'
reportsCommandArgs: ['36525d']
reportsImage: 'lukaszgryglicki/devstats-reports'
reportsRestartPolicy: 'Never'
reportsVolumeMountPath: '/data'
requestsBackupsCPU: '1000m'
requestsBackupsMemory: '2Gi'
requestsBootstrapCPU: '1000m'
requestsBootstrapMemory: '1Gi'
requestsCronsCPU: '1000m'
requestsCronsMemory: '2Gi'
requestsGrafanasCPU: '1000m'
requestsGrafanasMemory: '2Gi'
requestsPostgresCPU: '8000m'
requestsPostgresMemory: '32Gi'
requestsProvisionsCPU: '4000m'
requestsProvisionsMemory: '8Gi'
requestsReportsCPU: '200m'
requestsReportsMemory: '256Mi'
requestsStaticsCPU: '500m'
requestsStaticsMemory: '512Mi'
requestsVacuumCPU: '250m'
requestsVacuumMemory: '256Mi'
restoreFrom: 'https://devstats.cncf.io/'
secretType: Opaque
servicePodName: devstats-service
storageAccessModes: ReadWriteOnce
storageClass: openebs-hostpath
skipTemp: 1
# We're using patroni's autovacuum feature.
skipVacuum: 1
staticImage: 'lukaszgryglicki/devstats-static-default'
staticNReplicas: 1
syncCommand: devstats
syncCronHistoryLimit: 3
syncImage: 'lukaszgryglicki/devstats-minimal-test'
syncPodName: devstats
syncRestartPolicy: Never
sslEnv: prod
testServer: '1'
testsImage: 'lukaszgryglicki/devstats-tests'
testsPodName: devstats-tests
testsRestartPolicy: Never
vacuumCron: '0 0 * * 6'
vacuumCronHistoryLimit: 1
vacuumCommand: './devel/vacuum_all.sh'
vacuumImage: 'lukaszgryglicki/devstats-test'
vacuumPodName: 'devstats-vacuum'
vacuumRestartPolicy: Never
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
useFlags: '1'
useRepos: ''
useBackupsResourcesLimits: 1
useBootstrapResourcesLimits: 1
useCronsResourcesLimits: 1
useGrafanasResourcesLimits: 1
useProvisionsResourcesLimits: 1
usePostgresResourcesLimits: 1
useReportsResourcesLimits: 1
useStaticsResourcesLimits: 1
useVacuumResourcesLimits: 1
waitForBootstrap: 120
waitForPostgres: 30
projects:
  - proj: kubernetes
    url: k8s
    db: gha
    icon: 'k8s'
    org: 'Kubernetes'
    repo: 'kubernetes/kubernetes'
    cron: '7 * * * *'
    disk: 50Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-1'
    i: 0
  - proj: prometheus
    url: prometheus
    db: prometheus
    icon: 'prometheus'
    org: 'Prometheus'
    repo: 'prometheus/prometheus'
    cron: '8 * * * *'
    disk: 5Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-3'
    i: 1
  - proj: opentracing
    url: opentracing
    db: opentracing
    icon: 'opentracing'
    org: 'OpenTracing'
    repo: 'opentracing/opentracing-go'
    cron: '8 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-4'
    i: 2
  - proj: fluentd
    url: fluentd
    db: fluentd
    icon: 'fluentd'
    org: 'Fluentd'
    repo: 'fluent/fluentd'
    cron: '9 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-5'
    i: 3
  - proj: linkerd
    url: linkerd
    db: linkerd
    icon: 'linkerd'
    org: 'Linkerd'
    repo: 'linkerd/linkerd'
    cron: '9 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-6'
    i: 4
  - proj: grpc
    url: grpc
    db: grpc
    icon: 'grpc'
    org: 'gRPC'
    repo: 'grpc/grpc'
    cron: '10 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-7'
    i: 5
  - proj: coredns
    url: coredns
    db: coredns
    icon: 'coredns'
    org: 'CoreDNS'
    repo: 'coredns/coredns'
    cron: '10 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-9'
    i: 6
  - proj: containerd
    url: containerd
    db: containerd
    icon: 'containerd'
    org: 'containerd'
    repo: 'containerd/containerd'
    cron: '11 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-10'
    i: 7
  - proj: rkt
    url: rkt
    db: rkt
    icon: 'rkt'
    org: 'rkt'
    repo: 'rkt/rkt'
    cron: '11 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-11'
    i: 8
  - proj: cni
    url: cni
    db: cni
    icon: 'cni'
    org: 'CNI'
    repo: 'containernetworking/cni'
    cron: '11 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-12'
    i: 9
  - proj: envoy
    url: envoy
    db: envoy
    icon: 'envoy'
    org: 'Envoy'
    repo: 'envoyproxy/envoy'
    cron: '12 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-13'
    i: 10
  - proj: jaeger
    url: jaeger
    db: jaeger
    icon: 'jaeger'
    org: 'Jaeger'
    repo: 'jaegertracing/jaeger'
    cron: '12 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-14'
    i: 11
  - proj: notary
    url: notary
    db: notary
    icon: 'notary'
    org: 'Notary'
    repo: 'theupdateframework/notary'
    cron: '13 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-15'
    i: 12
  - proj: tuf
    url: tuf
    db: tuf
    icon: 'tuf'
    org: 'TUF'
    repo: 'theupdateframework/tuf'
    cron: '13 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-16'
    i: 13
  - proj: rook
    url: rook
    db: rook
    icon: 'rook'
    org: 'Rook'
    repo: 'rook/rook'
    cron: '13 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-17'
    i: 14
  - proj: vitess
    url: vitess
    db: vitess
    icon: 'vitess'
    org: 'Vitess'
    repo: 'vitessio/vitess'
    cron: '14 * * * *'
    disk: 5Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-18'
    i: 15
  - proj: nats
    url: nats
    db: nats
    icon: 'nats'
    org: 'NATS'
    repo: 'nats-io/gnatsd'
    cron: '14 * * * *'
    disk: 5Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-21'
    i: 16
  - proj: opa
    url: opa
    db: opa
    icon: 'opa'
    org: 'OPA'
    repo: 'open-policy-agent/opa'
    cron: '14 * * * *'
    disk: 5Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-22'
    i: 17
  - proj: spiffe
    url: spiffe
    db: spiffe
    icon: 'spiffe'
    org: 'SPIFFE'
    repo: 'spiffe/spiffe'
    cron: '15 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-23'
    i: 18
  - proj: spire
    url: spire
    db: spire
    icon: 'spire'
    org: 'SPIRE'
    repo: 'spiffe/spire'
    cron: '15 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-24'
    i: 19
  - proj: cloudevents
    url: cloudevents
    db: cloudevents
    icon: 'cloudevents'
    org: 'CloudEvents'
    repo: 'cloudevents/spec'
    cron: '15 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-25'
    i: 20
  - proj: telepresence
    url: telepresence
    db: telepresence
    icon: 'telepresence'
    org: 'Telepresence'
    repo: 'telepresenceio/telepresence'
    cron: '15 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-26'
    i: 21
  - proj: helm
    url: helm
    db: helm
    icon: 'helm'
    org: 'Helm'
    repo: 'helm/helm'
    cron: '16 * * * *'
    disk: 8Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-27'
    i: 22
  - proj: openmetrics
    url: openmetrics
    db: openmetrics
    icon: 'openmetrics'
    org: 'OpenMetrics'
    repo: 'OpenObservability/OpenMetrics'
    cron: '16 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-28'
    i: 23
  - proj: harbor
    url: harbor
    db: harbor
    icon: 'harbor'
    org: 'Harbor'
    repo: 'goharbor/harbor'
    cron: '17 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-29'
    i: 24
  - proj: etcd
    url: etcd
    db: etcd
    icon: 'etcd'
    org: 'etcd'
    repo: 'etcd-io/etcd'
    cron: '17 * * * *'
    disk: 4Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-30'
    i: 25
  - proj: tikv
    url: tikv
    db: tikv
    icon: 'tikv'
    org: 'TiKV'
    repo: 'tikv/tikv'
    cron: '17 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-31'
    i: 26
  - proj: cortex
    url: cortex
    db: cortex
    icon: 'cortex'
    org: 'Cortex'
    repo: 'cortexproject/cortex'
    cron: '18 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-32'
    i: 27
  - proj: buildpacks
    url: buildpacks
    db: buildpacks
    icon: 'buildpacks'
    org: 'Buildpacks'
    repo: 'buildpack/lifecycle'
    cron: '18 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-33'
    i: 28
  - proj: falco
    url: falco
    db: falco
    icon: 'falco'
    org: 'Falco'
    repo: 'falcosecurity/falco'
    cron: '18 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-34'
    i: 29
  - proj: dragonfly
    url: dragonfly
    db: dragonfly
    icon: 'dragonfly'
    org: 'Dragonfly'
    repo: 'dragonflyoss/Dragonfly'
    cron: '19 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-35'
    i: 30
  - proj: virtualkubelet
    url: virtualkubelet
    db: virtualkubelet
    icon: 'virtualkubelet'
    org: 'Virtual Kubelet'
    repo: 'virtual-kubelet/virtual-kubelet'
    cron: '19 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-36'
    i: 31
  - proj: kubeedge
    url: kubeedge
    db: kubeedge
    icon: 'kubeedge'
    org: 'KubeEdge'
    repo: 'kubeedge/kubeedge'
    cron: '21 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-43'
    i: 32
  - proj: brigade
    url: brigade
    db: brigade
    icon: 'brigade'
    org: 'Brigade'
    repo: 'Azure/brigade'
    cron: '21 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-44'
    i: 33
  - proj: crio
    url: crio
    db: crio
    icon: 'crio'
    org: 'CRI-O'
    repo: 'cri-o/cri-o'
    cron: '22 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-45'
    i: 34
  - proj: networkservicemesh
    url: networkservicemesh
    db: networkservicemesh
    icon: 'networkservicemesh'
    org: 'Network Service Mesh'
    repo: 'networkservicemesh/networkservicemesh'
    cron: '23 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-46'
    i: 35
  - proj: openebs
    url: openebs
    db: openebs
    icon: 'openebs'
    org: 'OpenEBS'
    repo: 'openebs/openebs'
    cron: '24 * * * *'
    disk: 10Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-47'
    i: 36
  - proj: opentelemetry
    url: opentelemetry
    db: opentelemetry
    icon: 'opentelemetry'
    org: 'OpenTelemetry'
    repo: 'open-telemetry/opentelemetry-java'
    cron: '24 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-48'
    i: 37
  - proj: all
    url: all
    db: allprj
    icon: 'cncf'
    org: 'All CNCF'
    repo: '-'
    cron: '27 * * * *'
    disk: 150Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-20'
    i: 38
  - proj: tekton
    url: tekton
    db: tekton
    icon: 'tekton'
    org: 'Tekton'
    repo: 'knative/build'
    cron: '22 * * * *'
    disk: 3Gi
    domains: [1, 0, 1, 0]
    ga: 'UA-108085315-39'
    i: 39
  - proj: spinnaker
    url: spinnaker
    db: spinnaker
    icon: 'spinnaker'
    org: 'Spinnaker'
    repo: 'spinnaker/spinnaker'
    cron: '20 * * * *'
    disk: 4Gi
    domains: [1, 0, 1, 0]
    ga: 'UA-108085315-38'
    i: 40
  - proj: jenkinsx
    url: jenkinsx
    db: jenkinsx
    icon: 'jenkinsx'
    org: 'Jenkins X'
    repo: 'jenkins-x/jx'
    cron: '22 * * * *'
    disk: 6Gi
    domains: [1, 0, 1, 0]
    ga: 'UA-108085315-41'
    i: 41
  - proj: jenkins
    url: jenkins
    db: jenkins
    icon: 'jenkins'
    org: 'Jenkins'
    repo: 'jenkinsci/jenkins'
    cron: '23 * * * *'
    disk: 40Gi
    domains: [1, 0, 1, 0]
    ga: 'UA-108085315-40'
    i: 42
  - proj: allcdf
    url: allcdf
    db: allcdf
    icon: 'cdf'
    org: 'All CDF'
    repo: '-'
    cron: '28 * * * *'
    disk: 50Gi
    domains: [1, 0, 1, 0]
    ga: 'UA-108085315-42'
    i: 43
  - proj: graphqljs
    url: graphqljs
    db: graphqljs
    icon: 'graphqljs'
    org: 'GraphQL JavaScript'
    repo: 'graphql/graphql-js'
    cron: '25 * * * *'
    disk: 3Gi
    domains: [1, 0, 0, 1]
    ga: ''
    i: 44
  - proj: graphiql
    url: graphiql
    db: graphiql
    icon: 'graphiql'
    org: 'GraphQL IDE'
    repo: 'graphql/graphiql'
    cron: '25 * * * *'
    disk: 3Gi
    domains: [1, 0, 0, 1]
    ga: ''
    i: 45
  - proj: graphqlspec
    url: graphqlspec
    db: graphqlspec
    icon: 'graphqlspec'
    org: 'GraphQL Spec'
    repo: 'graphql/graphql-spec'
    cron: '26 * * * *'
    disk: 3Gi
    domains: [1, 0, 0, 1]
    ga: ''
    i: 46
  - proj: expressgraphql
    url: expressgraphql
    db: expressgraphql
    icon: 'expressgraphql'
    org: 'Express GraphQL'
    repo: 'graphql/express-graphql'
    cron: '26 * * * *'
    disk: 3Gi
    domains: [1, 0, 0, 1]
    ga: ''
    i: 47
  - proj: graphql
    url: graphql
    db: graphql
    icon: 'graphql'
    org: 'GraphQL'
    repo: 'graphql/graphql-js'
    cron: '24 * * * *'
    disk: 30Gi
    domains: [1, 0, 0, 1]
    ga: ''
    i: 48
  - proj: cncf
    url: cncf
    db: cncf
    icon: 'cncf'
    org: 'CNCF'
    repo: 'cncf/landscapeapp'
    cron: '19 * * * *'
    disk: 30Gi
    domains: [1, 0, 0, 0]
    ga: 'UA-108085315-8'
    i: 49
  - proj: opencontainers
    url: opencontainers
    db: opencontainers
    icon: 'opencontainers'
    org: 'OCI'
    repo: 'opencontainers/runc'
    cron: '20 * * * *'
    disk: 3Gi
    domains: [1, 0, 0, 0]
    ga: 'UA-108085315-19'
    i: 50
  - proj: istio
    url: istio
    db: istio
    icon: 'cncf'
    org: 'Istio'
    repo: 'istio/istio'
    cron: '20 * * * *'
    disk: 8Gi
    domains: [1, 0, 0, 0]
    ga: ''
    i: 51
  - proj: knative
    url: knative
    db: knative
    icon: 'cncf'
    org: 'Knative'
    repo: 'knative/serving'
    cron: '21 * * * *'
    disk: 4Gi
    domains: [1, 0, 0, 0]
    ga: ''
    i: 52
  - proj: zephyr
    url: zephyr
    db: zephyr
    icon: 'cncf'
    org: 'Zephyr'
    repo: 'zephyrproject-rtos/zephyr'
    cron: '29 * * * *'
    disk: 8Gi
    domains: [1, 0, 0, 0]
    ga: ''
    i: 53
  - proj: linux
    url: linux
    db: linux
    icon: 'cncf'
    org: 'Linux'
    repo: 'torvalds/linux'
    cron: '29 * * * *'
    disk: 10Gi
    domains: [1, 0, 0, 0]
    ga: ''
    i: 54
  - proj: thanos
    url: thanos
    db: thanos
    icon: 'thanos'
    org: 'Thanos'
    repo: 'thanos-io/thanos'
    cron: '24 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-49'
    i: 55
  - proj: flux
    url: flux
    db: flux
    icon: 'cncf'
    org: 'Flux'
    repo: 'fluxcd/flux'
    cron: '25 * * * *'
    disk: 3Gi
    domains: [1, 1, 0, 0]
    ga: 'UA-108085315-50'
    i: 56
